env:
  node: true
  browser: true
  jest: true
  es2021: true
extends:
  - react-app
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  linebreak-style: ["error", "unix"],
  indent: ["warn", "tab", {
    "SwitchCase": 1
  }],
  quotes: ["error", "single", { "allowTemplateLiterals": true }],
  no-console: "off"
}
